epispliced_dir: "../data/Epispliced"
bam_dir: "../data/Epispliced/raw_data/{sample}.bam"
refgen_path: "../data/refgen/refgen.no_pseudogene.gtf"
sample_name: "../data/Epispliced/raw_data/sample_name.csv"
PPIXpress_dir: "../data/PPIXpress"