result_path: "../data/RBP2GO_snakemake/PPIN_vs_binding_time"
PPIXpress_result_path: "../data/RBP2GO_snakemake/PPIXpress"
mRNP_chronology_table_path: "../data/mRNP_chrono/mRNP_chronology_hsa_HeLa-v1.xlsx"